name: Model Training

on:
  push:
    branches:
      - main  # You can set this to your default branch

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run model training
        run: |
          python train_model.py  # Your training script, this should save the accuracy to a file

      - name: Get accuracy and update badge
        run: |
          ACCURACY=$(python get_accuracy.py)  # Python script that extracts the latest accuracy from model logs or output
          curl -X POST "https://img.shields.io/badge/Accuracy-${ACCURACY}%25-brightgreen" > badge.svg
          git add badge.svg
          git commit -m "Update accuracy badge"
          git push
